language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script: 
- yarn test
- yarn build
deploy:
  provider: heroku
  app: shrouded-crag-92043
  on:
    repo: joozybrain/todo-list-react-demo
  api_key:
    secure: Lt0ymVjsMcBbn59EBhSlmVNoKF3P38+BTXEnfTUPQrtiTR9PAjvxAIhFi7N8kuTsbbuJbv1wjpJUdTvhsTlfaieA9Ku5U4Wq4/+o1EPOO3Ht4ndET6/4GtGrzrZMhZVYyp5yar6nTtHOUL4h1tmemoXIBsZ9RBXzBVcTlIPglTImV2rCOneLtTaewEBDMdyJFNr22eagT0nhRF5RyM8t8fh13ENvQeYDqHyjQOdSxZi9zKrVSVi+TsFBv31qIGvi1uFGaTHJ3Mrneq3ADmkQfddS5kvnqvWyHqNSTg88/mS4cE1F3S62Dkxx1BAYEV3xdydV5VHVTXEhVfIaOSp3lBYdeLXnGv7DOK940IxXucA9KKlZ2ZwNcmu6o/saaLw2qa+hElFTobeDPAHpGztyOy4DdPQzp1R3bKtAX+JUMl3ZLKjb1YSkMXLhP87E/AHE9EoGlF1+BjJQ6GWlIYAeYXAK4osH+pINSJZ1WXnLHB9RHxYpBtWRqdqF1Jv18tEKVHsADwWmOOQW9FIcjTFxVuYwVJ3e3PS4vO1fwI2TVhzWk3SSC1JYxaahbgPHQVAOszCQPjusgYYCD6KRz2xrzlfPb1P6VFofKse7V+/hnQ2+iMvbaA/T+4zskgJnT3XYhcj74PMoFTOnOR2Y4au8p4qLqZlDXk1H9Jm3g50sev4=
