language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: shrouded-crag-92043
  on:
    repo: joozybrain/todo-list-react-demo
  api_key:
    secure: dad51ER9dHJTGQlPd+f09mfn8yepJQFfoWwR6Asg9Um41Hkp+wSoRt+wZDzna+0Ziim7wAEvn8bE/SYkVJJRroJsu+d4ehxewewYOF+FI3pSwwDSJv5CYJkmqLdMznJ0AygRoHKw20a09wvgdld2LXTUALdSTXYlB4U1RiOw9DaMmAKGJVsqV7rva8L8cAMGo3xlKb7tiJNYbaY32k/kZ8GBMnU7TH8FRoqW91RzlZc8XYQCF60tG4Sk+3OeBmFHg8sg+ZZIpcVF3EyPFqnoi7mc0n7VJfYYYWnNtxT0q53DmpjOOlK06NBDvCBLUVTzzznsPzs28DgsrlREELfPQlc8G80PG+pVu5krHRF2xIYQczmoLtWL7NFxliaeUSp+ZiCrx+bMzsQC6bSHUkD47cp7hsEO/RJTnzhs8SivvnsOglAUFtCIu9EcFbbpagaSOv4cOEEznS4IrMIgGT+/vODS4fJmtCi8U/cnPH5Vs9BRgPfsE4tWGlbwqoWiU0VwPor6E24RNFxpCIFcljM3cfHimb2dPQPEjba8o7oB8pTQ338CR60eN06JraN5YqoAktCyKsGywBULOx5GIoKjHt4U46ZrvRBB7M20+bX1myukms1HaOuO8mJbUBwczHGIFq2sW8LjX6l+SfrjlA/NysbPkSPqffkTCItLOoCXjSY=