language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script: 
- yarn test
- yarn build
deploy:
  provider: heroku
  app: shrouded-crag-92043
  on:
    repo: joozybrain/todo-list-react-demo
  api_key:
    secure: znZsjtYtR0VDZ+CXLX1eW+vlmWHgItUT3yOZGu+BEFEuwcT51hUzbMuWzIhig2fMPBCWcbpLNljmnLf91OWqF1FKhmTclHP+8nMAu18Kg+Wugsvg668XzOHdO3j0meon4ahR9H+9UmbNXlS62mOo1kUkgB+PBjz7kAth3S3D/TZe6EBNfW/JI5sUsLQyQuGFqLQOeEWd7tApQQtJRlS9hHsr36dL3PnCogPrRQxj9F0NEGN/8fhQQsSLBV5MWRQmFZJV+6tgv5gwzEmEdwgogbIsN7ER7olizQL9gkSy7CcMx+V0h0jlJURLO+LDlhAg0Ot8Pvcqd0p61jDkgEKYSEY1qVLS47MTlK4einb4KmhEinyo7pUVH5nZbwfRT0n6SfrziOlKhTs9GeIZ5jUy1Xxd4uQdwsV43mVLQyc6MNLfZF7GNvypY38jFB761qvgiGp0EiePGX/QDetvSodwFXLcYUXU4aCXxqisiZL+CRL1voNhIKQwcJuTMit322OQS0WDIv3ETkHSmO6FvOspuKpBFCeh8DPh2UE8b4s1T1wF3ReeFoyD2LrveZP/GBnBjrIPK4uYzol2Db/JHuBKAV0NfyOT1fkWX5W5MXEY+qpjba22toyZVMwX6N7RCd1JHR5C/BH/zcC1EzcAQtzDrxWszVbRIYmO/i2A3fNuI70=
