language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: shrouded-crag-92043
  on:
    repo: joozybrain/todo-list-react-demo
  api_key:
    secure: drGWvpj9KsO1bemyWofFGJhmZiDgRbgbq346WwBJn4Gp5e9uQYqrJhD9Q/o3h8R0WeuFLBQEQChs+pwAakqILHIGxoDCn9BlZC1egsPfX+/0CqYuK6dVMCFv6y0y+cPd3QxKwuSX/WNyopEEFRsMD72vV+ejVi9jRsSGjFzQMYfmD1uR3rzb0esrOYibPt4Ppuo+2V1uB01+6k15A8qk8eecrHy4td5D52cS8PZidGFQLmfx0ZKOL5yTymPvDBeJ6miWP+IwtRx/vmxVAq6r6gaMb82ia6tlv3EP7k0VDU7iwfsOs0l0ojxF+KON0VhLL9jQ+OK1jVIecbzNqYxrkSx9wTUFMcbXcx6B7x/NDuGPFdWdCdpfdSKxOSzgYsGlilMm3JN8f+Kmvw+aBenNjUAlPsjih0MUX6kVfDJeHwcctIKuqd61wqUFJ9OhwwwbgiQHvp7IuBNPPGFPr5Am7fStxTppdoHKMnzVr5tLzrAvtiQf6MocWG42lYYq2qVBedlF3Kusx8PiWc/9AT28OX29BpYCTLX+UEkNIJp2AZ38cpspGxq1RIMKHeNx/7RQazh5d2nnirG7QtaujYJtj2PdC1QSnbXiOsWsceHU1olU0qU0Lr4gdcWLcDnj5nAtdfWYrUfk92zpz2P05X1Gi1XcXUwrZC85WORYlc2MQ1c=
